### ISSUE TITLE
运行时界面空的

### ISSUE THREAD

**Issue by aiadaniel** [lsw5530/RPG_GameFramework#1]
是否资源没有提交？
客户端有没有简单的说明：如何从C#调用到lua的界面比如LoginForum.lua.txt

**Comment by lsw5530** [comment]
1.主要怕侵权就没上传所有的资源文件，AB包提供的是完整的，运行界面空白应该是没从CDN正确加载的原因。
2.演示的lua案例比较简单，由于我平时用的也不多。
